### PR TITLE
[WIP] Basic MVP

### PR DESCRIPTION
**Pull request by nouveller**
This should add the very basic functionality.

No merging just yet, still WIP. :bomb:

### CODE REVIEW

**Comment by nouveller** [comment]
@daviddarnes First steps! I thought we can do all the work in `develop`, then merge to master once we're happy, then PR to `gh-pages`. I see that's what you've been doing.

:smile:

**Comment by daviddarnes** [comment]
@nouveller sounds good man! I mean instead of `develop` we could always name branches as certain features or developments? That way it feels like we're applying chunks to `master` and then deploying to `gh-pages`. Rather than 1 to 1 passing of PRs.

**Comment by nouveller** [comment]
@daviddarnes Okay, sounds good. I was still in hack this in a night or two mentality, ha. I'll rename this branch and summarise what should be included in the feature.

**Comment by nouveller** [comment]
Moved to https://github.com/daviddarnes/currentstat.us/pull/5 and outlined tasks.

**Comment by daviddarnes** [comment]
@nouveller not a problem man! Only mentioned it because I thought it would be easier, I've got no gripes with getting stuck in. Hack first, organise later ;)

**Pull request closed without merging**
