### PR TITLE
making the 'submit' button open in a new tab

### PR DESCRIPTION
**Pull request by penelopehelen**
This has added in the functionality of when clicking the 'submit' link, it will force the browser to open a new tab. That way when someone like me goes a bit mental and wants to add more than one gif, its easier and I don't need to navigate back through to the page I was initially on

### CODE REVIEW

**Comment by daviddarnes** [comment]
@penelopehelen a solid addition, thank you. However I'm not sure about the style addition, `style="target-new: tab;`. I don't think that is a valid property? If you remove that part on your `new-tab` branch then I can merge it straight away :dancer:

**Comment by penelopehelen** [comment]
I'll have a check on this when I get home as I thought I'd gotten the right style in there as it uses the style to force the tab. But I'll have a proper look tonight 😊

**Comment by daviddarnes** [comment]
@penelopehelen you did get the new tab thing right, but it doesn't need to have the style bit :)

**Comment by penelopehelen** [comment]
Ah cool!! I'll do that when I get home 😊 can't access git at work 😟

**Comment by penelopehelen** [comment]
Done :) I'll get Ben to sanity check my code next time :)

**Comment by daviddarnes** [comment]
Thank you! Don't worry @penelopehelen, it's all part of the learning process.

**Pull request merged**
