### PR TITLE
Site structure

### PR DESCRIPTION
**Pull request by nouveller**
This should do the following.

- [x] Setup the basic CSS structure (no actual styling required, just linking it in the layout and setting up the files)
- [ ] Setup the basic JS structure (Bower? Some other solution? Currently dependencies come in via  CDN)
- [ ] Create the bare bones page that are required to get this to work
- [x] Setup basic JSON data source
- [ ] Misc. (anything else that allows us just to start coding)

### CODE REVIEW

**Comment by nouveller** [comment]
@daviddarnes This looks wicked! :heart_eyes:

**Comment by daviddarnes** [comment]
@nouveller thanks man :simple_smile:

**Comment by nouveller** [comment]
@daviddarnes You can now click a status and open a gif, not the final functionality. But I've updated `statuses.json` with some gifs and just wanted to "make it work".

**Comment by daviddarnes** [comment]
@nouveller "just make it work" is my kinda thing. Functionality is there, lets clean up a smash it online.

**Comment by daviddarnes** [comment]
@nouveller did some fun CSS stuff and added some share buttons. Would like to compare with my personal site just to make sure it's got all the little pre-launch bits in there.

**Comment by daviddarnes** [comment]
This is close to a full MVP now, thoughts on what's left @nouveller?

**Comment by daviddarnes** [comment]
Added our twitter handles to the footer, plus a submission url! Just creates an issue on GitHub.

**Comment by nouveller** [comment]
@daviddarnes You have done superb work, this is awesome.

I think for now, this is good to go live. You happy with it?

**Comment by daviddarnes** [comment]
@nouveller thanks man, but you've certainly done your part as well! I'm happy if you're happy!

We can iterate later and clean up some parts as we go along.

**Comment by nouveller** [comment]
Then, lets go!

**Pull request merged**
